# services:
#   app:
#     build: 
#       context: .
#       dockerfile: dockerfile
#     environment:
#       - PORT=3000
#     ports: 3000:3000
#     command: 
#       - ./bin/rails
#       - server
#       - -b
#       - 0.0.0.0
#     depends_on:
#       - db
#   db:
#     image: postgres
#     ports: 5432:5432