services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_LOG_LEVEL=debug
      - RAILS_MAX_THREADS=5
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase
      - SECRET_KEY_BASE=dummy
      - PORT=3000
    ports: 
      - "3000:3000"
    command: 
      - ./bin/rails
      - server
      - -b
      - 0.0.0.0
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports: 
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data

volumes:
  my_dbdata:
